### PR TITLE
Run scripts test nightly (alternative)

### PR DESCRIPTION
**Pull request by dweiss**

### CODE REVIEW

**Comment by dweiss** [comment]
I think something like this should simplify the workflow code and work?

**Comment by dweiss** [comment]
Uch. Sorry @mocobeta - I think we've overlapped in changing some of the files. Please take a look at the fork/ PR I created and take anything you like from there.

**Comment by mocobeta** [comment]
I resolved the conflicts so that we can merge this to the parent branch; thank you!

**Comment by mocobeta** [comment]
I would merge this now and see the CI results in #893.

**Pull request merged**
